### ISSUE TITLE
resolveHtml method strips off</link>

### ISSUE THREAD

**Issue by MilanLund** [Kentico/kontent-delivery-sdk-js#279]
### Brief bug description

I have a strong suspicion that the resolveHtml method strips off the `</link>` tag from an underlying template when resolving a rich text element. 

### Repro steps

My implementation is a bit complex so I outline the code example on a snippet taken from the documentation to see my point:

```
deliveryClient.item<Movie>('pain_and_gain')
    queryConfig({
      richTextResolver: (item: ContentItem, context) => {
        if (item.system.type == 'actor') {
          var actor = item as Actor;
          return `<link>${actor.name.value}</link>`;
        }
    })
  })
  .toObservable()
  .subscribe(response => {
    console.log(response.item.plot.resolveHtml());
  });
```

### Expected behavior

The expected output is something like:
`<link>Brad Pitt</link>`
But I get: 
`<link>Brad Pitt`

### Test environment

Platform/OS: Node 10.16.0, Windows 10
SDK version: 9.0.0

### Note

With that, I am trying to resolve an XML code for RSS feed. As the method name is resolveHtml, I guess there is some HTML parser behind. And as in HTML the `<link>` tag is self-closing, the parser "fixes" the code for me. Is that the case?
If so, is there any way I can resolve rich text without that smart HTML parser? Maybe I am just missing something. Thanks.

**Comment by Enngage** [comment]
I did some investigation and `link` tag is indeed stripped this way because it's invalid HTML - e.g. if you try [https://validator.w3.org/nu/#textarea](https://validator.w3.org/nu/#textarea) with

```
<!DOCTYPE html>
<html lang="en">
  <head>
     <title>a</title>
   </head>
<body>
   <p><link>Tom</link></p>
</body>
</html>
```
You can see that the `</link>` part is invalid. 

This is being stripped by the `parse5` html parser and there is no way around this. Until we have `json` support for rich text elements, there is nothing I could do about this (without writing own HTML parser which is kind of unrealistic). 

Closing as this is essentially proper behavior and there is no easy way to change it.
