### ISSUE TITLE
Creating Migration Guidelines from Version 10 to 11

### ISSUE THREAD

**Issue by hemmachat** [Kentico/kontent-delivery-sdk-js#331]
### Motivation

Helping/guiding developers who already have the existing code using delivery API version 10 and willing to upgrade to version 11.

### Proposed solution

Someone from Kontent team to create the migration guidelines with some sample code.

### Additional context

We have the existing code using @kentico/kontent-delivery v10.4.1 with @kentico/kontent-model-generator v3.2.0 and we are willing to upgrade to the latest version of the libraries. It seems to be quite a big change from our point as I have tried and facing some issues. For example:

- There is no documentation on how to migrate as your official documentation is not updated with the latest version: https://docs.kontent.ai/reference/delivery-api#operation/list-content-items.
- There are some breaking API changes such as pagination which is now accessible from "Response.response.data.pagination" and the properties are changes to "total_count" which I needed to read your source code to find out about it.
- The model generation, you change from using the "class" way to the "type" and "interface" way of TypeScript which I understand that it will be less code. As we already have some methods to access the properties in a short-form, so, having some guidelines will be helpful.

So, having a guideline on the migration will be super helpful for developers and it will save a lot of time. You guys already have a strong products but the documentation is still a bit lacking. Cheers to the team that always make better and smaller libraries.

**Comment by Enngage** [comment]
Hi @hemmachat,

Structurally, the response & method names are pretty much identical to v10. For example, the response is just "wrapped" in a data model, but you should be able to solve this by some sort of global replace in your project. The documentation has been update to use v11 as well (e.g. https://docs.kontent.ai/reference/delivery-api#operation/list-content-items) 

We are not preparing any more specific migration guide as you should be able to see code examples in the main readme.md and update your code based on those. It's true that there are breaking changes, but pretty much all of them can be solved very easily with replace or by moving your logic around (e.g. because the models are represented by types, you have to move the business logic from business models to some sort of helper functions or own classes).
