### ISSUE TITLE
Make resolvers in delivery async

### ISSUE THREAD

**Issue by Enngage** [Kentico/kontent-delivery-sdk-js#81]
Rich text & link resolvers could support returning of Promises/Observables so that client can run async code inside the resolver. Example:

```
queryConfig({
        richTextResolver: (item) => {
          console.log(item);

          const urlWithProxy = `https://cors-anywhere.herokuapp.com/${item.url.text}.json`;
          const response = await fetch(urlWithProxy);
          const json = await response.json();

          return `<link href="${json.stylesheet}" media="screen" rel="stylesheet" />${json.div}`;

          //return resolveGist(item.url.text);
        }
      });
```

**Comment by Enngage** [comment]
This will require significant refactoring. If someone is up to it, feel free to take it. I'll come back to this in next major version probably.

**Comment by Domitnator** [comment]
Any update on this? Still waiting for this feature!

**Comment by Enngage** [comment]
Hey, this is not currently in planning as it requires huge refactoring and changes in how resolvers would work. It is possible that RTE will support **json** output in (hopefully) near future so I will likely revisit this when it does as to avoid 2 significant refactoring.

**Comment by benmorana** [comment]
@Enngage - Any updates on when we could potentially expect this feature? We're looking to build an inline component that would allow content editors to show a listing of the 3 most recent pages of a given content type. This would then allow us to always resolve the three latest pages at build time without requiring content editors to keep those listings up to date manually in Kontent. Something like this: 
```
queryConfig({
  richTextResolver: async (item, client) => {
    const request = await client.search({ type: 'blog' }, {limit:3});
     return `<ul>${request.reduce((acc, elem) => { return  acc += `<li>${elem.title}</li>`}, '')}</ul>`
   }
});
```
Another feature that would be needed to be added for this work, is the ability to pass custom parameters in the resolveHtml() function that could then be available in the richTextResolver function when rendering the component ( in this example, it's the search client we've configured to limit the load on the Kentico REST API). Let me know if you'd like me to add an extra feature request for this, but thought I'd first mention it here since it'd probably be tied up with a refactoring of the richTextResolver :)

**Comment by Enngage** [comment]
@benmorana The next version of SDK now provides new way of resolving rich text and does provide an async version of browser rich text parser as can be seen in this test (https://github.com/Kentico/kontent-delivery-sdk-js/blob/vnext/test/browser/isolated-tests/resolvers/browser-rich-text-resolver/browser-rich-resolver-html-priority-async.spec.ts#L29) 

The preview version of the SDK will be released soon ;) For now, I'm closing this issue, but feel free to comment or reopen it.
